name: CD â€“ Kyverno Policies

on:
  workflow_call: 
 
jobs:
  apply-kyverno-policy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: Potluri-11/central-ci
          ref: main
          path: central-ci
      - name: Debug workspace (IMPORTANT)
        run: |
          echo "PWD:"
          pwd
          echo "Files:"
          ls -R
      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config
      - name: Apply Kyverno policies
        run: kubectl apply -f central-ci/policies/
