name: CD â€“ Kyverno Policies

on:
  push:
    paths:
      - "kyverno/**"

jobs:
  apply-policies:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
      - name: Apply Kyverno policies
        run: kubectl apply -f kyverno/
