name: Central Reusable CI Pipeline

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string

jobs:
  ci-job:
    runs-on: ubuntu-latest

    steps:
      - name: Build
        run: echo "Build passed"

      - name: Test
        run: |
          echo "Tests passed"
          exit 0

      - name: SBOM
        run: echo "SBOM generated"

      - name: Trivy
        run: echo "Trivy scan passed"

      - name: Cosign
        run: echo "Image signed"
